### ISSUE TITLE
Add JSpecify annotations to defaults

### ISSUE THREAD

**Issue by jvz** [apache/logging-parent#88]
As noted in https://issues.apache.org/jira/browse/LOG4J2-1477, JSpecify is the project specifying the one true nullability annotation standard. I experimented with creating copies of those annotations that use the JSR 305 nullability annotations to implement it, but it seems like it'd be easier to just use these annotations directly since they're only required at compile time. The use of these annotations would supersede any use of the old JSR annotations.

**Comment by ppkarwasz** [comment]
@jvz, can you list which tools currently support those annotations? I am mostly interested in Eclipse, IDEA, Spotbugs and some tool like NullAway or Checker Framework that guarantees that the code is NPE-free.

**Comment by jvz** [comment]
I have no idea if any support this yet. I like the annotation scheme at least, though, if we want to use our own packaged annotations instead based on JSR 305 like I tried out before. That approach at least works with existing tools until JSpecify is directly supported.

**Comment by jvz** [comment]
I just noticed that this can be done directly in Log4j for now. This will make it simpler to apply any rewrites to the annotations as tooling catches up. See https://github.com/apache/logging-log4j2/commit/2da4108da52653dbb43f00b0967f16917c6975c0 for the aliasing.

**Comment by GregDThomas** [comment]
> which tools currently support those annotations? I am mostly interested in Eclipse, IDEA, Spotbugs and some tool like NullAway or Checker Framework t

IntelliJ supports it (JetBrains are a member of the jspecify group - https://jspecify.dev/about)
There's details on a fork of the checker framework at https://github.com/jspecify/jspecify-reference-checker

No idea on Spotbugs/Eclipse I'm afraid.
