### ISSUE TITLE
Clean up Apache RAT configuration

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-parent#92]
Due to the [`RAT-355`](https://issues.apache.org/jira/browse/RAT-335) enhancement, Apache Rat 0.16 is now able to implicitly ignore most files ignored by Git.

This allows us to clean up the configuration from all the files that are also in a typical `.gitignore`.

**Comment by ppkarwasz** [comment]
This issue is a no-op for `logging-parent`, but should be applied to `logging-log4j2`.

I am keeping this issue open until apache/maven-apache-parent#185 is merged and we bump to a new version of the ASF parent.

**Comment by vy** [comment]
@ppkarwasz, instead of waiting for the next `org.apache:apache` release, we can

1. override the `org.apache.rat:apache-rat-plugin` version ourselves
1. create an issue to remove the override once the next `org.apache:apache` release arrives
1. ship this in `10.6.0`
